repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^tests/data/
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.202
    hooks:
      - id: ruff
