# Use root/example as user/password credentials
version: "3.1"
services:
  # Vue Frontend
  # mealie-frontend:
  #   image: mealie-frontend:dev
  #   build:
  #     context: ./frontend
  #     dockerfile: frontend.Dockerfile
  #   restart: always
  #   ports:
  #     - 9920:8080
  #   environment:
  #     VUE_APP_API_BASE_URL: "http://mealie-api:9000"
  #   volumes:
  #     - ./frontend/:/app
  #     - /app/node_modules

  # Fast API
  mealie-api:
    image: mealie-api:dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 9921:9000
    environment:
      db_type: sqlite
      TZ: America/Anchorage # Specify Correct Timezone for Date/Time to line up correctly.
    volumes:
      - ./app_data:/app_data
      - ./mealie:/app

  # mealie-docs:
  #   image: squidfunk/mkdocs-material
  #   restart: always
  #   ports:
  #     - 9922:8000
  #   volumes:
  #     - ./docs:/docs

