name: PR CI

on:
  pull_request:
    branches:
      - mealie-next

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yml

  container-scanning:
    name: "Trivy Container Scanning"
    uses: ./.github/workflows/partial-trivy-container-scanning.yml
  
  security-scanning:
    name: "CodeQL Security Scanning"
    uses: ./.github/workflows/codeql.yml
